<?xml version="1.0" encoding="UTF-8"?><testrun name="DaoTests.test2" project="JAVABOOK_my" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="Ch38.Tests.Dao.DaoTests" time="0.801" displayname="DaoTests" uniqueid="[engine:junit-jupiter]/[class:Ch38.Tests.Dao.DaoTests]">
    <testcase name="test2" classname="Ch38.Tests.Dao.DaoTests" time="0.801" displayname="test2()" uniqueid="[engine:junit-jupiter]/[class:Ch38.Tests.Dao.DaoTests]/[method:test2()]">
      <error>java.sql.SQLException: UserDao's Insert SQL Exception&#13;
	at Ch38.Domain.Dao.UserDaoImpl.insert(UserDaoImpl.java:61)&#13;
	at Ch38.Tests.Dao.DaoTests.test2(DaoTests.java:22)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
